// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\artem\Documents\Go_scripts\test_v_galery\internal\service\service.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	auth "github.com/theborzet/jwt_token/pkg/auth"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// IssueTokens mocks base method.
func (m *MockService) IssueTokens(userId, ipAddress string) (string, *auth.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueTokens", userId, ipAddress)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*auth.RefreshToken)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IssueTokens indicates an expected call of IssueTokens.
func (mr *MockServiceMockRecorder) IssueTokens(userId, ipAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueTokens", reflect.TypeOf((*MockService)(nil).IssueTokens), userId, ipAddress)
}

// RefreshTokens mocks base method.
func (m *MockService) RefreshTokens(userId, accessToken, refreshToken, ipAddress string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokens", userId, accessToken, refreshToken, ipAddress)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RefreshTokens indicates an expected call of RefreshTokens.
func (mr *MockServiceMockRecorder) RefreshTokens(userId, accessToken, refreshToken, ipAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokens", reflect.TypeOf((*MockService)(nil).RefreshTokens), userId, accessToken, refreshToken, ipAddress)
}
