basePath: /
definitions:
  handler.errorResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  handler.request:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  handler.successResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for managing time tracking tasks
  termsOfService: https://example.com/terms/
  title: Time Tracker API
  version: "1.0"
paths:
  /api/v1/auth/token/{userID}:
    post:
      consumes:
      - application/json
      description: Выдает пару Access и Refresh токенов для пользователя с указанным
        ID.
      parameters:
      - description: ID пользователя (GUID)
        in: path
        name: userID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.successResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Выдать токены
  /api/v1/auth/token/refresh/{userID}:
    post:
      consumes:
      - application/json
      description: Обновляет пару Access и Refresh токенов, используя предоставленные
        Refresh и Access токены.
      parameters:
      - description: ID пользователя (GUID)
        in: path
        name: userID
        required: true
        type: string
      - description: Тело запроса с токенами
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.successResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Обновить токены
swagger: "2.0"
